- RELEASE_NOTES.md
- deployment/conf/supported_apps_w_extensions.json
- staging_service/AutoDetectUtils.py
- staging_service/app.py
- staging_service/autodetect/Mappings.py
- tests/test_autodetect.py
Without doing a lot of restructuring of the app specs and autodetection logic, it seems to me the best way to handle gzipped files that we know are supported by apps is to preferentially pick the longest valid extension to get importers. This means that `*.gb.gz` will autodetect to Genbank rather than have Genbank and Decompress suggested.
It's a bit fragile if we start getting extensions with lots of dots in them, but that doesn't seem very likely.
The user can always pick Decompress from the dropdown if they wish.
416/473 lines are autogenerated.
> Support gzip for in scope bulk upload apps

- README.md
- staging_service/autodetect/GenerateMappings.py
- staging_service/autodetect/Mappings.py
* Change documentation to use the correct string ID rather than a
numerical ID for apps.
* Simplify and consistent-ify some format names
* Move MSA into regular bioinfo formats
* Change gzip specific variable names into more generic names in case
we want to add bzip
* Remove the unused extensions_flat variable in the type mapper
* Simplify looking up extensions for apps
These changes made no difference to the type mappings when the mapper
was re-run.
> Minor code & docs cleanup.

- deployment/conf/supported_apps_w_extensions.json
- staging_service/autodetect/GenerateMappings.py
- staging_service/autodetect/Mappings.py
- tests/test_autodetect.py
Currently you can assign multiple apps to a file type category *and* multiple
file extensions to a file type category. That means that given a file
extension and an app it's not always possible to determine the file category.
Further, these 2 degrees of freedom aren't necessary to correctly assign apps
to file extensions - allowing multiple apps per category allows that.
So
* ensure that file extensions only appear once in the file category map
* it turns out that deleting the custom categories fixed this issue
* Define the apps in a separate mapping from the category -> app mapping,
since currently the same app is defined multiple times, once per each
category.
This changes nothing in the resulting app mapping JSON other than the
ordering of some keys.
> Simplify type / app mapping

- README.md
- RELEASE_NOTES.md
- deployment/conf/supported_apps_w_extensions.json
- staging_service/app.py
- staging_service/autodetect/GenerateMappings.py
- tests/test_autodetect.py
This is primarily of benefit when an app takes 2 different file types as input.
Currently there's no way for the client to tell which file is which.
> Add file type / category to extension mappings

- README.md
- RELEASE_NOTES.md
- staging_service/app.py
- staging_service/metadata.py
- tests/test_app.py
Note that there is a showHidden parameter for listing files that will expose all dotfiles (including .globus_id, which may not be desirable)
> Hide dotfiles by default, disallow dotfile uploads

- README.md
- staging_service/app.py
The endpoints were displayed as h3 while their success and error children
were displayed as h2 which is odd
Also removed a  print statement that was a bit spammy during tests
closes #105
> README cleanup

- README.md
- RELEASE_NOTES.md
- deployment/conf/supported_apps_w_extensions.json
- staging_service/AutoDetectUtils.py
- staging_service/autodetect/GenerateMappings.py
- tests/test_app.py
- tests/test_autodetect.py
- no reason to duplicate the file type in every mapping
- leaves the per mapping file_type field unused for future, more sophisticated file type algorithms
> Move file type to file info

- staging_service/import_specifications/file_parser.py
- tests/import_specifications/test_file_parser.py
parsers for individual file types are provided by the resolver.
> DATAUP_549: Add general parser framework

- staging_service/import_specifications/file_parser.py
- tests/import_specifications/test_file_parser.py
https://docs.python.org/3/library/typing.html#typing.Tuple
Also don't use the deprectated `Callable` type hint
> Type hint tuples correctly

- docs/import_specifications.ADR.md
* Update and explain the template schema
* Describe the best effort parsing strategy
* Add an `incorrect_column_count` error
* Dial back on required logging for parse errors. Most of the stack traces
will not be useful.
For xSV files, since pandas drops data if a row has more columns than the first row, manually parse the first line and then pass the remainder of the file handle to pandas.
Tested with excel files - in that case pandas just duplicates the first cell X times in the header structure where X is the maximum column count in the data.
> DATAUP-549: Update ADR with new template, best effort parsing, etc

- staging_service/import_specifications/file_parser.py
- staging_service/import_specifications/individual_parsers.py
- tests/import_specifications/test_file_parser.py
- tests/import_specifications/test_individual_parsers.py
The idea behind this change is that the front end can provide detailed instructions re how to fix this error - e.g. look for an incorrect number of separators in xSV files or delete rows and columns outside the data block in Excel files.
> DATAUP-549: Add an incorrect column count error type

- .gitignore
- staging_service/import_specifications/file_writers.py
- tests/import_specifications/test_file_writers.py
Will eventually be hooked up to a service endpoint to allow the narrative
to generate import templates on command
@briehl heads up if you're interested
> DATAUP-682: Add import spec writers for xsv files

- staging_service/import_specifications/file_writers.py
- tests/import_specifications/test_file_writers.py
- tests/test_utils.py
Also modifies the return from the xSV writers to make it easier for calling methods to rewrite paths, e.g. full path -> staging service user path.
> DATAUP-682: Add Excel import template writer

- README.md
- RELEASE_NOTES.md
- staging_service/app.py
- staging_service/import_specifications/file_writers.py
- tests/import_specifications/test_file_writers.py
- tests/test_app.py
This is to support the extension list in the popup dialog in that design ticket. Since I was already working on the staging service and this was a very simple endpoint I figured I'd implement it well ahead of of time.
> DATAUP-648: Add import_filetypes endpoint

- RELEASE_NOTES.md
- staging_service/import_specifications/file_writers.py
- staging_service/import_specifications/individual_parsers.py
- tests/import_specifications/test_individual_parsers.py
Even leaving a blank line at the end of a csv or tsv file will make the parser puke
> DATAUP-691: Ignore blank lines in xSV files

- staging_service/app.py
- tests/test_app.py
Will automatically add a trailing slash to a request URL if needed to
match an endpoint, saving the user from having to worry about it.
> Add url normalization middleware

- RELEASE_NOTES.md
- staging_service/import_specifications/individual_parsers.py
- tests/import_specifications/test_individual_parsers.py
Pandas would replace missing header items with weird names like
`Unnamed: 2_level_0`. Pandas has enough quirks that it's not worth using it -
simpler to just use a low level csv parser.
> DATAUP-698: Fix ?sv files with missing header items getting strange key names

- RELEASE_NOTES.md
- staging_service/app.py
- staging_service/import_specifications/individual_parsers.py
- tests/import_specifications/test_individual_parsers.py
If an xSV file is opened and saved by Excel, it'll add trailing separators to
the end of the first header line. This fix ignores those separators.
> DATAUP-727: Fix an import spec parse bug re trailing separators

- RELEASE_NOTES.md
- staging_service/app.py
- staging_service/import_specifications/file_writers.py
- tests/import_specifications/test_file_writers.py
Ensure that the file writer throws an error if the types parameter is empty.
> DATAUP-746: empty `types` dictionary throws an error

- RELEASE_NOTES.md
- staging_service/app.py
1.3.4 was never deployed to CI, let alone prod, so no need for another
version bump
> Merge versions to 1.3.4

- RELEASE_NOTES.md
- staging_service/app.py
- staging_service/metadata.py
- tests/test_metadata.py
If a file is listed or checked for existence and an UPA is added to the file
before the file is completely uploaded, the metadata will never be fully
created.
> PTV-1767: Fix file metadata incomplete return bug
