run_tests.sh
staging_service/app.py
tests/test_app.py

Tickets:
https://kbase-jira.atlassian.net/browse/SCT-268
list endpoint doesn't work with /list
https://kbase-jira.atlassian.net/browse/SCT-267
existence endpoint has various problems

staging_service refactor

---

staging_service/metadata.py
tests/test_app.py

metadata() endpoint has 2 major bugs:
1. it breaks when metadata file needs to be rebuild
2. due to legacy code, some metadata doesn't have all needed information resulting staging UI display none for line_count, md5, first_10_lines and last_10_lines.

SCT-278 fixing metadata endpoint

---

staging_service/JGIMetadata.py
staging_service/app.py
staging_service/auth2Client.py
staging_service/metadata.py
staging_service/utils.py
tests/test_app.py

Bugfix:
Fix jbi-metadata endpoint to return a JSON format of JBI metadata
https://kbase-jira.atlassian.net/browse/SCT-288
Make existence endpoint return consistent with other endpoints
https://kbase-jira.atlassian.net/browse/SCT-276
Fix server error 500 with empty or invalid token
https://kbase-jira.atlassian.net/browse/SCT-269
Fix server error 500 when md5sum breaks
https://kbase-jira.atlassian.net/browse/SCT-290

jbi_metadata/existence endpoint bugfixes

---

requirements.txt
staging_service/app.py
tests/test_app.py

SCT-249 addming more tests

---

staging_service/app.py

@scanon @sychan Adding .globus_id existence check. This method also creates one if it's not existing.

SCT-566 adding globusid check

---

staging_service/app.py

SCT-645 catching more errors

---

staging_service/app.py
staging_service/metadata.py
tests/test_app.py

avoid calling multiple system subprocess.

Fix error handling

---

staging_service/app.py
tests/test_app.py

better handle missing destPath or upload param

Fixing missing uploads param

---

staging_service/app.py

Reverts kbase/staging_service#43

Revert "remove necessary break"

---

.gitignore
README.md
staging_service/app.py
tests/test_app.py

Should do what it says on the tin. @Tianhao-Gu  Let me know what you think

SCT-1547: Add download endpoint

---

Dockerfile
README.md
README_AND_SETUP.rst
globus.cfg
requirements.txt
staging_service/app.py
staging_service/utils.py

This PR adds endoints to add and remove ACLS. See [readme.rst](README_AND_SETUP.rst)

SCT-1509 - Add endpoints to add and remove acls

---

staging_service/app.py
staging_service/utils.py

Fix method name and error logging

---

Dockerfile
RELEASE_NOTES.md
deployment/conf/deployment.cfg
deployment/conf/local.cfg
deployment/conf/testing.cfg
docker-compose.yml
prune_acls.py
staging_service/app.py
staging_service/utils.py

Add functionality to kbase-concierge

DEVOPS-163: Concierge

---

Dockerfile
RELEASE_NOTES.md
deployment/conf/deployment.cfg
deployment/conf/local.cfg
deployment/conf/testing.cfg
docker-compose.yml
prune_acls.py
staging_service/app.py
staging_service/utils.py
tests/test_app.py

* Make sure release notes are filled out
* Make sure version is tagged after merge

Develop -> Master

---

globus.cfg

updated endpoint it to point at globus connect server endpoint

updated endpoint id

---

RELEASE_NOTES.md
staging_service/metadata.py

DATAUP-296 Fix file preview

---

RELEASE_NOTES.md
deployment/conf/supported_apps_w_extensions.json
staging_service/autodetect/GenerateMappings.py
staging_service/autodetect/Mappings.py

This updates the autodetected mappings returned by the autodetect endpoint

DATAUP-331 DATAUP-265 Update mappings

---

deployment/conf/supported_apps_w_extensions.json
staging_service/autodetect/Mappings.py

What it says on the tin.
I assume we don't add tests for config file changes, but let me know if we do.

DATAUP-473: Add .gb and .gbff to genbank auto detect

---

README.md
RELEASE_NOTES.md
deployment/conf/supported_apps_w_extensions.json
staging_service/AutoDetectUtils.py
staging_service/app.py
staging_service/autodetect/GenerateMappings.py
tests/test.env.example
tests/test_autodetect.py

Remove apps key from importer mapping endpoint

---

deployment/conf/supported_apps_w_extensions.json
staging_service/autodetect/GenerateMappings.py
staging_service/autodetect/Mappings.py

I'll leave this PR open until #119 is approved, but no reason not to start reviews now.
Signifies that the file contains upload specifications for other staging area
files rather than data to upload

DATAUP-548 Add an import specification type

---

.github/workflows/run_tests.yml
Dockerfile
README.md
RELEASE_NOTES.md
requirements.txt
tests/test_autodetect.py

Needed to update a few libraries for compatibility
Also minor simplifications to a test fixture

Update to python 3.9

---

Pipfile
Pipfile.README.md
Pipfile.lock
requirements.txt

Also add a frozendict install for future use

Add a pipfile for convenience

---

staging_service/app.py
staging_service/utils.py

Removed some documentation lines that aren't true based on examing the code

Minor documentation clean up

---

staging_service/import_specifications/file_parser.py
tests/import_specifications/test_file_parser.py

Isolates the code from the rest of the staging service code, makes it easy to
test

DATAUP-549: Define the API for parsing import spec files

---

Pipfile
Pipfile.lock
requirements.txt
staging_service/import_specifications/individual_parsers.py
tests/import_specifications/test_individual_parsers.py

DATAUP-549 Add xSV parser

---

tests/test_autodetect.py

Remove test autodetect print

---

Pipfile
Pipfile.lock
requirements.txt

Sync master with develop

---

RELEASE_NOTES.md
staging_service/app.py
staging_service/import_specifications/individual_parsers.py
tests/import_specifications/test_individual_parsers.py

This was a comedy of errors...

Fix bug adding empty entries for blank lines in xSV parser

---

README.md
staging_service/app.py

Bump version in app.py
